// GENERATED by scripts/gen-patients.mjs from data/synthetic-patients/index.json. Do not edit.
export interface SyntheticPatient { id: string; name: string; age: number; sex: string; memberSince: string; }

export const PATIENTS: SyntheticPatient[] = [
  {
    "id": "SYN-001",
    "name": "David Park",
    "age": 51,
    "sex": "male",
    "memberSince": "2024-05-01"
  },
  {
    "id": "SYN-002",
    "name": "Marcus Lee",
    "age": 46,
    "sex": "male",
    "memberSince": "2024-10-01"
  },
  {
    "id": "SYN-003",
    "name": "Priya Raman",
    "age": 58,
    "sex": "female",
    "memberSince": "2025-01-15"
  },
  {
    "id": "SYN-004",
    "name": "Sofia Alvarez",
    "age": 38,
    "sex": "female",
    "memberSince": "2025-11-01"
  },
  {
    "id": "SYN-005",
    "name": "Robert Hayes",
    "age": 63,
    "sex": "male",
    "memberSince": "2023-01-20"
  },
  {
    "id": "SYN-006",
    "name": "Elena Brooks",
    "age": 44,
    "sex": "female",
    "memberSince": "2025-06-01"
  },
  {
    "id": "SYN-007",
    "name": "James Whitaker",
    "age": 55,
    "sex": "male",
    "memberSince": "2024-02-01"
  }
];
